### ISSUE TITLE
Styling hooks for other add-ons - Uploads

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms-layout-styles#154]

**Comment by Much2tall** [comment]
styles/includes/Admin/Submenu.php (57)
array needs to be filterable so that add-ons can register their field styles.

i.e. styles/includes/Config/FieldTypeSections.php defines styling settings for File Uploads starting at line 320. Those settings would exist in File Uploads, and any other add-ons would register similar settings to the same filter.

**Comment by kjohnson** [comment]
@Much2tall `FiledTypeSections.php` is filterable with `ninja_forms_styles_field_type_section`.
See `FiledTypeSections.php#Line3`.
